### PR TITLE
Add Summarizer and API endpoints

### LINKED ISSUE #12: Add code for the summarizer
## Summary

Add the model that performs summarization on the text.

## Expected behaviour

When called through an API, the model will take in the text, process it and then return a summarized text.

### LINKED ISSUE #13: API for Summarizer
## Summary

Wrap the model in an API to be able to access it from the frontend

## Expected behaviour

API call made from the frontend triggers the model to summarize the text and return the summarized text.

### PR DESCRIPTION
**Pull request by routrohan**
## Issue Fix
Fixes #12, fixes #13 

## Description

- Added the summarizer script along with the nltk data to be used (stopwords, tokenizers, etc)
- Created an endpoint to call the summarizer and pass the text to be summarized.

## Reviewers

@dotrachit @HarshCasper @Imperial-lord

### CODE REVIEW

**Comment by dotrachit** [comment]
Great stuff @routrohan! Can you add the `__pycache__` file in `.gitignore` before we merge this PR?

**Review by dotrachit — CHANGES_REQUESTED** [review]
Great stuff @routrohan! Can you add the `__pycache__` file in `.gitignore` before we merge this PR?

**Comment by routrohan** [comment]
@dotrachit Please confirm if the requested changes have been implemented properly.

**Review by dotrachit — APPROVED** [review]
LGTM! ✨

**Pull request merged**
